<?php
/**
 * FileName: seftranslate.php
* Date: 09/09/2015
* Development Aleksey Pakholkov, Andrey Kvasnevskiy - OrdaSoft(http://ordasoft.com)
* @package SefTranslate
* @copyright 2010 Andrey Kvasnevskiy-OrdaSoft(akbet@mail.ru);Aleksey Pakholkov
* Homepage: http://www.ordasoft.com
* @version: 5.0 free
* @license GNU General Public license version 2 or later; see LICENSE.txt
**/


// Don't allow direct linking
if( !defined( '_VALID_MOS' ) && !defined( '_JEXEC' ) ) die( 'Direct Access to '.basename(__FILE__).' is not allowed.' );
require_once(JPATH_SITE."/administrator/components/com_seftranslate/toolbar.seftranslate.php");
$GLOBALS['task'] = $task = JRequest::getVar( 'task', "" );
$GLOBALS['option'] = $option = JRequest::getVar( 'option', "com_seftranslate" );

$document = JFactory::getDocument();
$mosConfig_live_site = JURI::root(true);
$document->addCustomTag('<link rel="stylesheet" href="'.
    $mosConfig_live_site.'/administrator/components/com_seftranslate/includes/seftranslate.css" type="text/css" />');
if (version_compare(JVERSION, "3.0.0", "ge")) {
  $document->addCustomTag('<link rel="stylesheet" href="'.
    $mosConfig_live_site.'/administrator/components/com_seftranslate/includes/seftranslate_j3.css" type="text/css" />');
}

  //print_r("|".$task);exit;
  switch ($task) {
    case 'clear_map':
      clear_map();
      setting();
         break;
    case 'apply':
      apply();

    default:
      setting();
      break;
  }
function clear_map()
{
  if(is_file(JPATH_SITE."/components/com_seftranslate/map.cch"))
  {
    unlink(JPATH_SITE."/components/com_seftranslate/map.cch");
  }

}
function apply()
{
  $seftranslate_configuration['release']['version']=JArrayHelper::getValue($_REQUEST,'release_version',"");
  $seftranslate_configuration['site_language']=JArrayHelper::getValue($_REQUEST,'site_language',"en");
  $seftranslate_configuration['map_lang']=implode("|",JArrayHelper::getValue($_REQUEST,'map_lang',"en") );
  $seftranslate_configuration['cache_map']=JArrayHelper::getValue($_REQUEST,'cache_map',"0");
  $seftranslate_configuration['translator']=JArrayHelper::getValue($_REQUEST,'translator',"bing");
  $seftranslate_configuration['api_google_translate_key']=JArrayHelper::getValue($_REQUEST,'api_google_translate_key',"");
  $seftranslate_configuration['api_bing_client_secret']=JArrayHelper::getValue($_REQUEST,'api_bing_client_secret',"");
  $seftranslate_configuration['api_bing_client_id']=JArrayHelper::getValue($_REQUEST,'api_bing_client_id',"");
  $seftranslate_configuration['azure_subscription_key']=JArrayHelper::getValue($_REQUEST,'azure_subscription_key',"");
  $seftranslate_configuration['azure_region']=JArrayHelper::getValue($_REQUEST,'azure_region',"");
  $seftranslate_configuration['update']=JArrayHelper::getValue($_REQUEST,'update',"1");


  setParams($seftranslate_configuration);
  JFactory::getApplication()->enqueueMessage( "Settings is saved" );  
}
function setParams($seftranslate_configuration)
  {
    $set = "<?php\n";
    $set .= "// Do not edit this file. Generated by admin script.\n";
    $set .= "// Translate Configuration file\n";
    $set .= "// General Informations \n";
    $set .= "\$seftranslate_configuration['release']['version']='" . $seftranslate_configuration['release']['version'] ."';\n";
    $set .= "\$seftranslate_configuration['site_language']='" . $seftranslate_configuration['site_language'] ."';\n";
    $set .= "\$seftranslate_configuration['map_lang']='" . $seftranslate_configuration['map_lang'] ."';\n";
    $set .= "\$seftranslate_configuration['cache_map']='" . $seftranslate_configuration['cache_map']."';\n";
    $set .= "\$seftranslate_configuration['translator']='" . $seftranslate_configuration['translator']."';\n";
    $set .= "\$seftranslate_configuration['api_google_translate_key']='" . $seftranslate_configuration['api_google_translate_key']."';\n";
    $set .= "\$seftranslate_configuration['api_bing_client_secret']='" . $seftranslate_configuration['api_bing_client_secret']."';\n";
    $set .= "\$seftranslate_configuration['api_bing_client_id']='" . $seftranslate_configuration['api_bing_client_id']."';\n";
    $set .= "\$seftranslate_configuration['azure_subscription_key']='" . $seftranslate_configuration['azure_subscription_key'] ."';\n";
    $set .= "\$seftranslate_configuration['azure_region']='" . $seftranslate_configuration['azure_region'] ."';\n";

    $set .= "\$seftranslate_configuration['update']='" . $seftranslate_configuration['update']."';\n";

    $fd = fopen(JPATH_SITE."/components/com_seftranslate/languages.conf.php", "w" );
    fwrite( $fd, $set );
    fclose( $fd );
  }
function setting()
{

    $seftranslate_configuration=Array();
    {
      require_once(JPATH_SITE."/components/com_seftranslate/languages.conf.php");
    }
    //print_r($seftranslate_configuration);
?>
    <form action="index.php" method="post" name="adminForm" id="adminForm" >
<?php

    if(version_compare(JVERSION, '3.0.0', 'ge')) {
      //Create Pane
            $options = Array();
      echo JHtml::_('tabs.start', 'tab_group_id', $options);
      //Create 1st Tab
            echo JHtml::_('tabs.panel', JText::_('General'), 'panel_1_id');
      settingGeneral($seftranslate_configuration);
      //Create 2nd Tab

            echo JHtml::_('tabs.panel', JText::_('Map'), 'panel_2_id');
      settingsMap($seftranslate_configuration);
      echo JHtml::_('tabs.panel', JText::_('About'), 'panel_3_id');
      about($seftranslate_configuration);
      //Create 3rd Tab
      echo JHtml::_('tabs.panel', JText::_('Help'), 'panel_4_id');
      help($seftranslate_configuration);
      //End Pane
      echo JHtml::_('tabs.end');

    } else {

      jimport('joomla.html.pane');
      //Get JPaneTabs instance
      $myTabs = JPane::getInstance('tabs', array('startOffset'=>0));
      $output = '';
      //Create Pane
      echo $myTabs->startPane( 'pane' );
      //Create 1st Tab
      echo $myTabs->startPanel( 'General', 'tab1' );
      settingGeneral($seftranslate_configuration);
      echo $myTabs->endPanel();

      echo $myTabs->startPanel( 'Map', 'tab2' );
      settingsMap($seftranslate_configuration);
      echo $myTabs->endPanel();

      echo $myTabs->startPanel( 'About', 'tab3' );
      about($seftranslate_configuration);
      echo $myTabs->endPanel();
      //End Pane
      echo $myTabs->startPanel( 'Help', 'tab4' );
      help($seftranslate_configuration);
      echo $myTabs->endPanel();

      echo $myTabs->endPane();

    }

?>

      <input name="task" id="task" value="apply" type="hidden">
      <input name="option" id="option" value="com_seftranslate" type="hidden">
    </form>
<?php
}
function about($seftranslate_configuration)
{
  echo "<div>";
  if(is_file(JPATH_SITE."/administrator/components/com_seftranslate/doc/about.html"))
  {
    $fp = fopen(JPATH_SITE."/administrator/components/com_seftranslate/doc/about.html", "r");
    $contents = fread($fp, filesize(JPATH_SITE."/administrator/components/com_seftranslate/doc/about.html"));
    fclose($fp);
    echo $contents;

  }
  else
  {
    echo "Sorry! File not found.";
  }
  echo "</div>";

}
function help($seftranslate_configuration)
{
  echo "<div>";
  if(is_file(JPATH_SITE."/administrator/components/com_seftranslate/doc/help.html"))
  {
    $fp = fopen(JPATH_SITE."/administrator/components/com_seftranslate/doc/help.html", "r");
    $contents = fread($fp, filesize(JPATH_SITE."/administrator/components/com_seftranslate/doc/help.html"));
    fclose($fp);
    echo $contents;

  }
  else
  {
    echo "Sorry! File not found.";
  }
  echo "</div>";


}
function settingGeneral($seftranslate_configuration)
{
    $lang_list=parse_ini_file(JPATH_SITE."/components/com_seftranslate/languages.ini");
    $keys = array_keys( $lang_list );
    // iterate through styles
    $langs=Array();
    foreach( $keys as $key )
    {
      if($key!="UNKNOWN")
      {
        $t=new t_langs();
        $t->key=$lang_list[$key];
        $t->title=ucfirst(strtolower($key));
        $langs[]=$t;
      }
    }
  //just simly copy as previous
  $translate_list=Array();
  $translate_list['bing']='bing';
  $translate_list['gtranslate']='gtranslate';
  $keys=array_keys($translate_list);
  $trans=Array();
  foreach($keys as $key){
    if($key!="UKNOWN"){
      $t=new t_langs;
      $t->key=$translate_list[$key];
      $t->title=ucfirst(strtolower($key));
      $trans[]=$t;
    }
  }

  ?>
  <table>
    <tr>
      <td>Site Language:</td>
      <td>
        <?php  echo '<input type="hidden" value="'.$seftranslate_configuration['release']['version'].'" name="release_version" />';  ?>
        <?php
        echo JHTML::_('select.genericlist',  $langs, 'site_language', '', 'key', 'title', $seftranslate_configuration['site_language'], 'site_language' );
        ?>
      </td>
      <td>
        <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="The main language of your site." alt="info">';?>
      </td>
    </tr>
        <tr>
      <td>Use bing or Google API for translate:</td>
      <td>
        <?php
        echo JHTML::_('select.genericlist',  $trans, 'translator', '', 'key', 'title', $seftranslate_configuration['translator'], 'translator' );
        ?>
      </td>
      <td>
  <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="The main language of your site." alt="info">';?>
      </td>
    </tr>
        <tr>
      <td>Key Google API Translate:</td>
      <td>
       <input type="text" name="api_google_translate_key" value="<?php if(isset($seftranslate_configuration['api_google_translate_key'])) echo $seftranslate_configuration['api_google_translate_key'];?>" class="inputbox"/>
      </td>
      <td>
  <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Set key Google API Translate." alt="info">';?>
      </td>
    </tr>
    <!--tr>
      <td>Bing API Translate - client secret:</td>
      <td>
       <input type="text" name="api_bing_client_secret" value="<?php if(isset($seftranslate_configuration['api_bing_client_secret'])) echo $seftranslate_configuration['api_bing_client_secret'];?>" class="inputbox"/>
      </td>
      <td>
  <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Set client secret for Bing API Translate." alt="info">';?>
      </td>
    </tr>
    <tr>
      <td>Bing API Translate - client ID:</td>
      <td>
        <input type="text"  name="api_bing_client_id" size="60" value="<?php echo $seftranslate_configuration['api_bing_client_id']; ?>" />
      </td>
      <td>
  <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Set client ID for Bing API Translate." alt="info">';?>
      </td>
    </tr-->
    <tr>
      <td>AZURE subscription key</td>
      <td>
        <input type="text"  name="azure_subscription_key" size="60" value="<?php echo $seftranslate_configuration['azure_subscription_key']; ?>" />
      </td>
      <td>
  <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Set subscription key for AZURE Cognitive Services for Microsoft Translator API" alt="info">';?>
      </td>
    </tr>    
    <tr>
      <td><?php echo "AZURE region"; ?></td>
      <td>
        <input type="text"  name="azure_region" size="20" value="<?php echo $seftranslate_configuration['azure_region']; ?>" />
      </td>
      <td>
  <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Please set region for Azure" alt="info">';?>
      </td>
    </tr>
  </table>


  <?php

}
function settingsMap($seftranslate_configuration)
{
  //print_r(explode("|",$seftranslate_configuration['map_lang']));exit;
  $lang_list=parse_ini_file(JPATH_SITE."/components/com_seftranslate/languages.ini");
  $keys = array_keys( $lang_list );
    // iterate through styles
    $langs=Array();
    foreach( $keys as $key )
    {
      if($key!="UNKNOWN")
      {
        $t=new t_langs();
        $t->key=$lang_list[$key];
        $t->title=ucfirst(strtolower($key));
        $langs[]=$t;
      }
    }
  ?>
  <table>

    <tr>
      <td>Translate page on Site Map:</td>
      <td>
        <?php
        echo JHTML::_('select.genericlist',  $langs, 'map_lang[]', 'class="inputbox" multiple size="8"', 'key', 'title', explode("|",$seftranslate_configuration['map_lang']), 'map_lang');
        ?>
      </td>
      <td>
        <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Set language when need translate site map." alt="info">';?>
      </td>
    </tr>
    <tr>
      <td>Use cache for Site Map:</td>
      <td>
          <fieldset id="jform_sitemap" class="radio btn-group">
        <input type="radio" name="cache_map" id="jform_sitemap_01" value="0"
        <?php echo ($seftranslate_configuration['cache_map'] == 0) ? " checked=\"checked\"" : " "; ?> />
        <label for="jform_sitemap_01" style="clear:none">No</label>
        <input type="radio" name="cache_map" id="jform_sitemap_02" value="1"
        <?php echo ($seftranslate_configuration['cache_map'] == 1) ? " checked=\"checked\"" : " "; ?> />
        <label for="jform_sitemap_02" style="clear:none">Yes</label>
          </fieldset>
      </td>
      <td>
          <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Set language when need translate site map." alt="info">';?>
      </td>
    </tr>
    <tr>
      <td>Clear cache Site map:</td>
      <td>

        <?php
        if(is_file(JPATH_SITE."/components/com_seftranslate/map.cch"))
        {
        ?>
        <input type="submit" value="Clear..." id="log" onClick="adminForm.task.value='clear_map'">
        <?php }else{ ?>
          Cache is clear.
        <?php } ?>
      </td>
      <td>
        <?php echo '<img src="'.JURI::base().'components/com_seftranslate/images/info.png" title="Clear you cache for site map." alt="info">';?>
      </td>
    </tr>
  </table>
  <?php


}
function settingCache()
{

}


class t_langs
{
  var $key;
  var $title;
}

?>
