<?php
// Do not edit this file. Generated by admin script.
// Translate Configuration file
// General Informations 
$seftranslate_configuration['release']['version']='4.5.0 free';
$seftranslate_configuration['site_language']='es';
$seftranslate_configuration['map_lang']='zh-CN|zh-TW|pt|vi';
$seftranslate_configuration['cache_map']='0';
$seftranslate_configuration['translator']='bing';
$seftranslate_configuration['api_google_translate_key']='';
$seftranslate_configuration['api_bing_client_secret']='';
$seftranslate_configuration['api_bing_client_id']='';
$seftranslate_configuration['azure_subscription_key']='';
$seftranslate_configuration['update']='1';
